export const SET_BOOKING_TICKET = "SET_BOOKING_TICKET";
export const SET_PASSENGER_INFO = "SET_PASSENGER_INFO";
export const SET_INFANT_INFO = "SET_INFANT_INFO";
export const SET_PASSENGER_CONTACT_INFO = "SET_PASSENGER_CONTACT_INFO";
export const SET_FARE_INFO = "SET_FARE_INFO";
export const RESET_ALL = "RESET_ALL";
export const UPDATE_PSG_INFO_ON_QTY_CHANGE = "UPDATE_PSG_INFO_ON_QTY_CHANGE";
export const SET_BOOKED_TICKET_INFO = "SET_BOOKED_TICKET_INFO";
