export const SET_BOOKING_TICKET = "SET_BOOKING_TICKET";
export const SET_PASSENGER_INFO = "SET_PASSENGER_INFO";
export const SET_PASSENGER_CONTACT_INFO = "SET_PASSENGER_CONTACT_INFO";
export const SET_FARE_INFO = "SET_FARE_INFO";
